PGF-468: create MenuListItem component
PayGreen/paygreen-ui pull request #100
Opened 2020-10-09 13:10 UTC by OliviaGometz

- Création d'un nouveau composant : MenuListItem, qui une variante du MenuItem. Cela permet d'alléger leurs props respectives, de bien différencier ces deux composants aux styles, comportements et localisations distinctes (ce qui résout les bugs de lib)
- Retrait des props useless sur MenuItem
- Refacto des hover sur le composant Logo (pour éviter les bugs de lib)
- Fix du style des flèches sur le composant Message + ajout d'orientations supplémentaires (bottom). À tester sur des écrans de tailles différentes pour observer les effets du `left` et du `right` corrigés.
- Fix du style des MenuList dans les MenuSecondary
- Fix de la largeur des ListItem contenus dans une List avec un style dashed
- Fix sur l'affichage des DaTableHeadCell qui contiennent une checkbox sur mobile
- Update des packages utilisés par UI

**Sans impact sur les composants :** 

- Retrait des <a href="#"> dans les stories où il était possible de les remplacer par des <button type="button"> (évite, en cas de clic, de sortir de storybook)

2020-10-09 15:40 UTC, pierrick-lefebvre requested changes

2020-10-09 15:50 UTC, fanya3 requested changes

2020-10-09 15:50 UTC, fanya3 commented on src/lib/Header/Header.stories.js
>                      >
dans cette story le logo a encore la props 'hasHoverRight' du coup le hover ne fonctionne pas :) 
j'ai fait une recherche, elle y est encore dans les stories de Layout, de MenuGroup et de Sidebar

2020-10-09 15:50 UTC, fanya3 commented on src/lib/MenuList/MenuList.stories.js
>              )}
alors chez moi sur storybook, en grand format j'ai le menu list qui ne se voit pas  il faut scroller vers le bas pour le retrouver :) 
j'ai testé en rajoutant en parent juste une ` <div style={{position:'relative'}}>` en parent ça permet de gérer le placement absolute de menulist

2020-10-09 15:50 UTC, fanya3 commented on src/lib/MenuSecondary/MenuSecondary.stories.js
> +                    <MenuItem>Login</MenuItem>
c'est normal qu'on perde les icons en mobile ? tu trouvais que ça faisait trop?

2020-10-09 15:50 UTC, fanya3 commented on src/lib/MenuSecondary/MenuSecondary.stories.js
> +                    colorTheme={colorThemeOptions.secondary}
quand le MenuItem a une props isClickable={false} il est de facto en gris nan? du coup le colorTheme secondary ne sert à rien ici?? :)

2020-10-09 16:50 UTC, fanya3 commented
@OliviaGometz j'ai fait un test d'intégration en local dans le BO, tout a l'air de marcher! juste un point, j'ai intégré le menu secondary, si on est en bout de menu à l'extrème droite le menulist étant en absolute verticalement centré par rapport au menuItem, il sort de l'écran à droite... on considère cela comme hors cas d'usage ou tu fais un fix pour ça??  
![menulist hover](https://user-images.githubusercontent.com/43522873/95610279-58547400-0a60-11eb-954c-0c225fe62e8d.png)

2020-10-12 08:24 UTC, OliviaGometz commented on src/lib/MenuSecondary/MenuSecondary.stories.js
> +                    <MenuItem>Login</MenuItem>
C'est ça, vu que j'ai rajouté des sous-liens avec des icons, je trouvais que ça faisait trop d'icons sur mobile :) (mais il est tjs possible d'en mettre, cf. la story du MenuGroup ! :D

2020-10-12 08:26 UTC, OliviaGometz commented on src/lib/MenuSecondary/MenuSecondary.stories.js
> +                    colorTheme={colorThemeOptions.secondary}
Tout à fait, je corrige ! :D

2020-10-12 08:29 UTC, OliviaGometz commented
@fanya3 nickel alors ! :D et ouais, à moins de rajouter une props pour gérer l'alignement du MenuList par rapport à son parent (auquel cas il sera plus centré :/), on va devoir considérer que c'est hors cas d'usage :/

2020-10-12 08:43 UTC, fanya3 approved these changes

2020-10-12 10:10 UTC, pierrick-lefebvre approved these changes

2020-10-12 12:21 UTC, merged