WIP-PGF-323: creation of skeletonItem and skeleton components
PayGreen/paygreen-ui pull request #101
Opened 2020-10-14 15:08 UTC by fanya3

## Infos :
voir ticket PGF-323

## Test : 
- `yarn storybook`
- aller à SkeletonItem et Skeleton

@OliviaGometz 
- j'ai le même problème de non surcharge des margins des enfants par le composant Grid pour Skeleton et SkeletonItem (plus ça va moins je comprends pourquoi ça marche sur Box...)  , ce qui fait que les enfants sont collés sauf quand on rajoute des gridgap ou en mode "column".... à toi de jouer!! :) merciiiiiii

2020-10-19 06:58 UTC, MattMattC approved these changes

2020-10-19 06:58 UTC, MattMattC commented on src/lib/Grid/Grid.stories.js
> +                </Box>
Indentation ?

2020-10-20 15:03 UTC, pierrick-lefebvre approved these changes

2020-10-21 12:48 UTC, OliviaGometz commented on src/lib/Grid/Grid.stories.js
ça a l'air résolu, bizarre que le commentaire soit pas fermé 😮

2020-10-23 07:12 UTC, OliviaGometz commented on src/lib/SkeletonItem/style/base.js
> +        );
Alors là, je te propose d'écrire ça à la place : 

```
        background-image: linear-gradient(
            -60deg,
            ${props => transparentize(1, props.theme.wab.white00)} 40%,
            ${props => transparentize(0.8, props.theme.wab.white00)} 40% 60%,
            ${props => transparentize(1, props.theme.wab.white00)} 60%
        );
```
Explications : 

1. Ne jamais utiliser "transparent" dans un dégradé : ça marche bien sur les navigateurs dignes de ce nom, mais sur des vieux trucs nazes (Safari) y'a une gestion un peu naze de l'opacité des couleurs dans un dégradé : pour Safari, transparent = noir désopacifié. Du coup, quand tu fais un dégradé blanc vers transparent, tu te retrouves avec un lieu de dégradé en gris à moitié opaque, c'est absolument dégueulasse. Le tricks, c'est donc de prendre la couleur de base de ton dégradé et de passer l'alpha à 0, comme ça ça empêche Safari de faire de la merde.

2. Utilise pas le rgba, mais plutôt le transparentize de polished (`import { transparentize } from 'polished';`), comme ça c'est bien la couleur du thème qui est utilisée.

3. Le reste de la proposition, c'est une version un peu revue du dégradé, je te laisse tester et me dire ce que tu en penses ! :D

2020-10-23 07:13 UTC, OliviaGometz commented on src/lib/SkeletonItem/style/base.js
> +    @keyframes loading {
utilise le `keyframes` de styled-components plutôt (en plus ça t'évite d'avoir à trouver un nom d'animation) :)

2020-10-23 07:15 UTC, OliviaGometz commented on src/lib/SkeletonItem/style/index.js
> +              `};
Bon bah du coup tjs pareil, si on pouvait caser cet énorme bout de code ailleurs et l'appeler tranquillou ici ce serait top ! :D

2020-10-23 11:59 UTC, fanya3 commented on src/lib/Skeleton/Skeleton.js
> +        let paddingDirection = 'padding' + direction;
tout est basé sur box

2020-10-23 12:00 UTC, fanya3 commented on src/lib/Skeleton/Skeleton.js
> +const Skeleton = ({ children, padding, margin, ...rest }) => {
oubli dans les manips :(

2020-10-23 12:01 UTC, fanya3 commented on src/lib/Skeleton/Skeleton.js
> +    skeletonType: PropTypes.oneOf(Object.values(skeletonTypeOptions)),
orde alphabetique quand y en a beaucoup?

2020-10-23 12:08 UTC, fanya3 commented on src/lib/Skeleton/style/SkeletonTypes.js
> +                            style={{ width: '100%' }}
oui mais elle va pas plus loin que sa propre dimension d'origine, quand on met une width en xl ou none, l'image ne suit pas sinon

2020-10-23 12:12 UTC, fanya3 commented on src/lib/Skeleton/style/SkeletonTypes.js
> +                        marginBottom={spaceOptions.lg}
faut voir comment on change la simulation de l'image alors....

2020-10-23 12:14 UTC, fanya3 commented on src/lib/Skeleton/style/base.js
> +              `};
et donc de refacto sur tous les composants concernés???

2020-10-23 12:25 UTC, fanya3 commented on src/lib/Skeleton/style/base.js
> +                        )};
ben les DaTableRow changent de hauteur (notamment avec ou sans checkbox) , il me semblait qu'on avait décidé ça d'entrée, tu penses au final que c t pas un bon choix??

2020-10-23 12:33 UTC, fanya3 commented on src/lib/SkeletonItem/SkeletonItem.js
> +        <SkeletonItemBase hasChildren={children} {...rest}>
j'ai découvert mieux entre temps sur le BO Green , on va mettre ça : hasChildren={!!children} 
 https://medium.com/better-programming/javascript-bang-bang-i-shot-you-down-use-of-double-bangs-in-javascript-7c9d94446054

2020-10-23 12:34 UTC, fanya3 commented on src/lib/SkeletonItem/SkeletonItem.stories.js
> +    .add('SkeletonItem with children', () => (
alors c'est parce que dans l'absolu on pourrait y mettre n'importe quel child

2020-10-23 12:37 UTC, fanya3 commented on src/lib/SkeletonItem/SkeletonItem.stories.js
> +            blockWidth={select(
pour moi il marche nickel (en terme de comportement). mais j'ai oublié d'enlever la height dans la story, le but c'est de montrer qu'l a une hauteur et largeur propre de part ses children mais qu'on peut forcer la width au besoin.

2020-10-27 11:18 UTC, fanya3 commented
@OliviaGometz j'ai fait toutes les modifs dont on a parlé, en spécifique : 
- concernant l'effet graphique skeleton chargement , j'ai adouci sur un côté (pour moi ça fait + chargement) mais on garde un côté net donc ça reste péchu, tu me dis ce que tu en penses, c'est toi qui tranches :) 
- concernant l'ajout du padding  customisable pour le skeleton en type ImageCard , on avait parlé de passer la props padding qui serait appliquée aux enfants en tant que margin (pour garder l'image plein pot) sauf que avec cette histoire de stocker les responsive padding/margin dans le fichier shared/spaces.js et comment il est implémenté en transversal dans les composants, ça m'a paru + simple de passer l'image en absolute pour la sortir du flux, de rajouter aux textes un margin-top de la hauteur de l'image et de laisser se faire le padding/ responsivePadding en automatique et exactement comme partout dans les autres composants.

2020-10-30 10:51 UTC, OliviaGometz requested changes
@fanya3 j'adore l'effet modifié, pour moi c'est parfait ! 😍 
Je crois que je vois ce que tu veux dire, pour le padding et l'image, et ça me va très bien, j'y vois aucune objection 👍 

Aussi, pense bien à virer le yarn.lock 😄 

Le SkeletonItem rectangle et circle me semble toujours énorme (même le tiny est très grand) par contre :/

Enfin, il faudrait faire en sorte que la hauteur de l'image dans le skeleton card soit fonction de la largeur de la card, comme c'est le cas dans les card (si tu vas dans la story Card > Card with image, tu peux tester, la largeur de la card change aussi la hauteur de l'image pour que ce soit plus équilibré/éviter que les proportions d'une même image change trop en fonction de la largeur de la Card qui la contient). Idéalement, il faudrait reproduire ce comportement dans le Skeleton :)

2020-10-30 10:51 UTC, OliviaGometz commented on src/lib/Skeleton/style/index.js
> +    ${responsiveMarginStyle};
remonte ça au-dessus du CardBase, y'a pas de raison de "couper" le style du Skeleton :)

2020-10-30 10:51 UTC, OliviaGometz commented on src/lib/SkeletonItem/SkeletonItem.js
> +        let marginDirection = 'margin' + direction;
(je unresolve vu que j'ai pas eu ma réponse xD)

2020-10-30 10:51 UTC, OliviaGometz commented on src/lib/SkeletonItem/style/base.js
> +        props.blockWidth === 'auto'
doit y avoir une constante pour ce "auto" :)

2020-10-30 10:51 UTC, OliviaGometz commented on src/lib/SkeletonItem/style/base.js
> +        props.blockWidth === 'auto'
(ça y est à 2 autres reprises d'ailleurs)

2020-10-30 10:51 UTC, OliviaGometz commented on src/lib/Skeleton/style/SkeletonTypes.js
> +const WrapperContent = styled.div`
perso je l'aurais appelé "AbsoluteContent" pour qu'on comprenne que son seul but est de sortir son contenu du flux :)

2020-10-30 10:51 UTC, OliviaGometz commented on src/lib/Skeleton/style/SkeletonTypes.js
> +                {/* this div is necessary to avoid border radius style applied by Card to its children*/}
ce commentaire mériterait de se trouver au-dessus de la div du premier composant :)

Ici, je te suggère d'appliquer plutôt une class CSS (style `content`) sur la div, et comme ça tu pourras la cibler dans le CSS pour lui ajouter son margin-top) : à relire et à comprendre, ce sera nettement plus clair ! :D

2020-10-30 10:51 UTC, OliviaGometz commented on src/lib/Skeleton/style/base.js
> +    & > :last-child {
utiliser plutôt une classe css pour cibler cet élément :)

2020-10-30 10:51 UTC, OliviaGometz commented on src/lib/Skeleton/Skeleton.stories.js
> +            paddingTop={select(
Pour moi tu peux virer le paddingTop/Right/Left et Bottom de la story (pareil pour sa copine du dessous), c'est pas un truc super indispensable à tester en live :)

2020-11-06 10:52 UTC, OliviaGometz requested changes

2020-11-06 10:52 UTC, OliviaGometz commented on src/lib/Grid/Grid.stories.js
>                  spaceOptions,
Pour le fichier du dessus : ⏫ 

![image](https://user-images.githubusercontent.com/32125579/98356574-11887880-2024-11eb-9f45-b417b3be561d.png)

2020-11-06 10:52 UTC, OliviaGometz commented on src/lib/Skeleton/style/SkeletonTypes.js
> +                <div>
Bon vu qu'il y a le package-json à virer, j'en profite pour dire que tu as zappé de remettre le commentaire du "pourquoi une div" dans une Card (à cause des arrondis, moi je m'en souviens bien mais le moi de dans 4 mois il aura totalement zappé, c'est archi sûr) 😆

2020-11-06 10:52 UTC, OliviaGometz commented on src/lib/Skeleton/style/SkeletonTypes.js
> +                {/* this div is necessary to avoid border radius style applied by Card to its children*/}
ah bah tiens, le fameux commentaire 😆 il est pas au bon endroit du coup, faudrait le remonter là où je t'ai laissé mon précédent commentaire 😄

2020-11-06 10:52 UTC, OliviaGometz commented on src/theme/theme.base.js
>          sm: '80px',
Pour le fichier du dessous ⏬ 

![image](https://user-images.githubusercontent.com/32125579/98357634-c707fb80-2025-11eb-8097-263ce47b9e14.png)

2020-11-06 11:18 UTC, fanya3 commented on src/lib/Skeleton/style/SkeletonTypes.js
> +                {/* this div is necessary to avoid border radius style applied by Card to its children*/}
mais j'ai pas compris quand tu as dis remonte sle au premier j'ai compris premier element dans le composant et non premier composant de la page ... my bad..

2020-11-06 11:18 UTC, fanya3 commented on src/theme/theme.base.js
>          sm: '80px',
![mistake](https://user-images.githubusercontent.com/43522873/98360518-3a137100-202a-11eb-9260-66980683ccb7.jpg)

2020-11-06 13:47 UTC, OliviaGometz approved these changes

2020-11-06 15:32 UTC, merged