PGF-484: create Histogram component
PayGreen/paygreen-ui pull request #103
Opened 2020-10-30 08:40 UTC by OliviaGometz

- Réorganisation de plusieurs stories pour retrouver plus facilement l'Histogram
- Ajout de fonctionnalités (position de flèche, couleurs) au composant Message pour qu'il puisse être utilisé dans le composant HistogramBar
- Fix de l'Icon pour qu'il puisse accepter des classes CSS custom (rien à voir avec l'Histogram, on en avait besoin pour fixer son comportement dans le ClickableBlock - fix passé en scred)
- Petit fix de marges dans la story du ClickableBlock (il y avait des choses qui étaient bizarres)
- Création de l'HistogramBar
- Création de l'Histogram

2020-11-04 13:22 UTC, fanya3 requested changes

2020-11-04 13:26 UTC, fanya3 commented
![histo bo](https://user-images.githubusercontent.com/43522873/98116913-47552200-1ea9-11eb-95a5-5492670bd186.png)
l'intégration ds le BO marche bien :)  par contre on est d'acc on ne peut pas créer d'alignement notamment en largeur avec les autres éléments à part en jouant sur le padding des bars et leur largeur??
est ce qu'on rajouterais pas juste une props align pour pouvoir choisir à minima de la centrer ou autre? t'en penses quoi?

2020-11-06 14:15 UTC, OliviaGometz commented on src/lib/Histogram/Histogram.js
> +    hasYaxisMin: PropTypes.bool,
Pour le `hasRelativeYaxis` tu as raison c'est pas clair, je l'ai renommé `isRelativeYaxis` 👍 

En revanche pour le `hasYaxisMin` et `hasYaxisMax`, c'est exactement ce que ça veut dire : est-ce que l'axe y a un min et un max ? (après c'est en effet, in fine, pour savoir si on affiche le min et le max qui existent par ailleurs, mais j'évite d'utiliser `display` en début de nom de props parce que contrairement à `has` ou `is`, il informe pas sur le fait que la props attendue est un booléen : le `display` on s'en sert par exemple pour les Grid avec le `displayType` (qui renvoie à flex, grid, column) : pour éviter de tout mélanger, je me suis contentée pour l'instant de is et has en booléen, c'est parfois un peu moins "anglais" mais au moins on sait direct ce qu'on doit mettre dedans 😄 

Et pour le `maxValue`, je m'en sers pas uniquement pour l'axe Y en fait : il me sert à set une valeur custom dans la variable `max` qui, elle, me sert à plein d'endroits (et pas uniquement dans l'affichage de l'axe Y) : la maxValue a un impact direct sur la hauteur des barres, donc elle est primordiale même lorsqu'elle n'est pas affichée sur l'axe Y 😄 

![image](https://user-images.githubusercontent.com/32125579/98375819-f37e4080-2042-11eb-8a63-457be8560171.png)

2020-11-06 16:05 UTC, OliviaGometz commented on src/lib/Histogram/Histogram.stories.js
> +                    isLabelVisible={false}
Pour l'instant ça marche bien avec des labels ultra courts (typiquement, des numéros de jour), mais en effet ça se chevauchera si y'a de longs labels et qu'ils sont tous en isLabelVisible !
Dans l'immédiat on n'a pas besoin de gérer ça, mais dans le futur on fera une évolution pour ça oui ! (pour l'instant je laisse tel quel pour pas perdre trop de temps, ça marche pour ce que c'est censé faire 👍 )

2020-11-06 16:09 UTC, OliviaGometz commented
> ![histo bo](https://user-images.githubusercontent.com/43522873/98116913-47552200-1ea9-11eb-95a5-5492670bd186.png)
> l'intégration ds le BO marche bien :) par contre on est d'acc on ne peut pas créer d'alignement notamment en largeur avec les autres éléments à part en jouant sur le padding des bars et leur largeur??
> est ce qu'on rajouterais pas juste une props align pour pouvoir choisir à minima de la centrer ou autre? t'en penses quoi?

Ouais ce sera bien d'avoir la main sur l'alignement de l'histogram, pareil pour moi c'est une évolution qu'on pourra faire plus tard quand le besoin se rencontrera 😄

2020-11-06 16:15 UTC, OliviaGometz commented on src/lib/HistogramBar/style/index.js
> +            pointer-events: initial;
Elle sert à reset ça, défini un peu plus bas : 

![image](https://user-images.githubusercontent.com/32125579/98388454-13b5fb80-2053-11eb-8c05-3696eaa1be30.png)

(si tu passes la souris sur le Message, ça lui permet de rester affiché même si t'es plus sur la zone permettant de l'ouvrir, c'est plus intuitif et pratique 😄 )

Et sinon j'm'en balec d'IE 10 🤣 c'est bien supporté ailleurs : 

![image](https://user-images.githubusercontent.com/32125579/98388812-7f986400-2053-11eb-8d0c-ce2f6fd5ce06.png)

Si on doit s'adapter à IE 10 on fait plus de grid déjà (et le pointer events est nettement moins critique s'il bug que le grid, globalement) 😄

2020-11-09 09:33 UTC, fanya3 approved these changes

2020-11-09 09:35 UTC, merged