Pgf 530 update datepicker
PayGreen/paygreen-ui pull request #104
Opened 2020-11-02 14:23 UTC by fanya3

## Détails : 
- Ajouts de fonction onChange pour récupérer la valeur du datepicker 
- Ajouts de gestion d'erreur  et d'une props "resetDate" pour resetter la date si une mauvaise date est entrée via l'input (date hors limite des maximum/minimum dates ou date non existante ex : 13/13/2020)
- Ajout d'une props isActive sur le Dropdown pour pouvoir prendre la main sur l'ouverture/fermeture du calendar en le combinant avec la méthode pour reset la date

## Comment tester : 
- yarn storybook
- dropdown : vérifier que le comportement est normal
- datepicker : rentrer des "mauvaises" dates via l'input, au clic à côté la date doit être reset soit selon la resetDate fournie soit avec la valeur par défaut (date du jour)

2020-11-04 13:03 UTC, fanya3 commented on src/lib/DatePicker/DatePicker.js
> +// const defaultDateFormat = localeConfig['pg-' + localeDefault].longDateFormat.L;
oh putain!

2020-11-04 13:06 UTC, fanya3 commented on src/lib/DatePicker/DatePicker.js
> +        ) {
euh mais là tu vérifies pas la validité des maximumDate et minimumDate, nan? (pierrick l'avait mis, je l'ai gardé)

2020-11-06 10:14 UTC, OliviaGometz requested changes
Au fait, y'a pas de MAJ des fichiers test.js à faire pour le DatePicker, vu tous les changements apportés ? :)

2020-11-06 10:14 UTC, OliviaGometz commented on src/lib/DatePicker/DatePicker.js
>      colorStatus: PropTypes.oneOf(Object.values(formStatusOptions)),
tu t'en doutais, je verrais bien une propTypes function pour le onChange sur le DatePicker (les autres sous-composants pas besoin vu qu'ils sont pas accessibles à l'extérieur) 😄

2020-11-06 10:14 UTC, OliviaGometz commented on src/lib/DatePicker/DatePicker.stories.js
> +                    locale={localeDefault}
Plus de placeholder non plus du coup ?

2020-11-06 10:14 UTC, OliviaGometz commented on src/lib/DatePicker/DatePicker.stories.js
> +                moment().startOf('month').format('DD/MM/YYYY'),
le startOf('month') sert à quoi ici au fait ? :) (vraie question)

2020-11-06 10:14 UTC, OliviaGometz commented on src/lib/DatePicker/CalendarCell/CalendarCell.js
> +
pour une fois je dirais que l'espace ici est pas indispensable, surtout si y'en a pas avant le if 😄

2020-11-06 10:26 UTC, fanya3 commented on src/lib/DatePicker/DatePicker.stories.js
> +                    locale={localeDefault}
alors la locale c un oubli de reset du coup je remets le custom,
et pour le placeholder, je suis partie sur un date picker présenté plutot comme ses cas d'usage cad avec une date définie par défaut (jour actuel) et non sans valeur (c'est comme ça sur react date picker) et ça coreespond à comment on l'implémente ds le BO.

2020-11-06 10:35 UTC, fanya3 commented on src/lib/DatePicker/DatePicker.stories.js
> +                moment().startOf('month').format('DD/MM/YYYY'),
c'etait pour definir la valeur de départ dans la story, vu que pierrick avait mis en minimum date la date du jour -1mois et maximudate +1 mois ça me semblait cohérent

2020-11-06 10:41 UTC, fanya3 commented on src/lib/DatePicker/DatePicker.stories.js
> +                moment().startOf('month').format('DD/MM/YYYY'),
c'est la dérive du bo où on les a tous mis au début du mois, mais en fait je peux juste mettre la date du jour :)

2020-11-06 13:38 UTC, OliviaGometz requested changes

2020-11-06 13:38 UTC, OliviaGometz commented on src/lib/DatePicker/DatePicker.js
> +        if (onChange) {
du coup si onChange est une props required, t'es pas obligée de laisser le if ici 😄

2020-11-06 13:38 UTC, OliviaGometz commented on src/lib/DatePicker/DatePicker.js
> +        if (onChange) {
idem là :)

2020-11-06 13:38 UTC, OliviaGometz commented on src/lib/DatePicker/DatePicker.js
> +            setSelectedDate(moment(defaultDate, dateFormat));
je viens juste réaliser que ce serait plus logique d'écrire ça : 

```
if (moment(value, dateFormat).isValid() === false) {
    const defaultDate =
        resetDate && moment(resetDate, dateFormat, true).isValid()
            ? resetDate
            : moment().format(dateFormat);
setSelectedDate(moment(defaultDate, dateFormat));
} else if (moment(maximumDate, dateFormat, true).isValid() && moment(value, dateFormat).isAfter(moment(maximumDate, dateFormat))) {
setSelectedDate(moment(maximumDate, dateFormat));
} else if (moment(minimumDate, dateFormat, true).isValid() && moment(value, dateFormat).isBefore(moment(minimumDate, dateFormat))) {
setSelectedDate(moment(minimumDate, dateFormat));
}
```

1. On set la minimum date si la date renseignée est trop vieille, ou on set la maximum date si la date renseignée est trop récente (plus logique).
2. Comme on se sert de la defaultDate qu'à cet endroit-là, tu peux définir la constante à cet endroit-là, à relire c'est plus logique 😄

2020-11-06 14:17 UTC, OliviaGometz approved these changes

2020-11-06 15:24 UTC, merged