PGF-647: Update of dropdown and datepicker
PayGreen/paygreen-ui pull request #123
Opened 2021-02-15 09:55 UTC by fanya3

## Ce qui a été fait : 
- Dropdown : rajout d'un context pour pouvoir gérer la fermeture du dropdown via le click sur un bouton/link en plus du clic à l'extérieur et rajout d'un composant DropdownControl qui passe soit directement le onClick() (pour un bouton ou un link, y a t-il d'autres cas qui seraient utiles à part le 'a' et le 'button' ?) soit le hook complet [setOpen, isOpen] à son enfant => @OliviaGometz ça me permet dans le BO de passer le hook au composant PopinUser qui à l'intérieur gère comme il veut la fermeture de la popin (utile pour fermer via le select de langue notamment)
- Datepicker : intégration direct du context de gestion de fermeture du DropDown via le hook useDropdown => au clic sur les dates le datepicker se ferme
- @OliviaGometz je t'ai rajouté les tests vu qu'il a fallu que je rajoute les contexts pour les tests côté datepicker pour qu'ils passent

## Comment tester:
- tester la fermeture via la nouvelle story ds le Dropdown et via la story du Datepicker
- tester le contrôle et reset interne des dates via la story du datepicker, tester que les différents resets se font bien selon que le datepicker ait une resetDate, une minimumDate, une maximumDate ou les 3 ou rien du tout...:)

2021-02-15 10:56 UTC, OliviaGometz reviewed
> pour un bouton ou un link, y a t-il d'autres cas qui seraient utiles à part le 'a' et le 'button' ?

Là je vois pas, ça me semble être les cas les plus génériques, et pour le reste tu as prévu une solution pour contourner, donc c'est nickel pour moi ! 😄

2021-02-15 10:56 UTC, OliviaGometz commented on src/lib/DatePicker/Calendar/Calendar.test.js
> +import { DropdownContext } from '../../Dropdown/DropdownContext';
vu que le DateContextProvider est contenu dans un dossier context, est-ce qu'on gagnerait pas en termes de cohérence de chemins de fichiers à faire la même pour le DropdownContext ? :)

2021-02-15 10:56 UTC, OliviaGometz commented on src/lib/DatePicker/CalendarCell/CalendarCell.js
> +import { useDropdown } from '../../Dropdown/DropdownContext';
à placer idéalement au-dessus de l'import de DateContext 😄

2021-02-15 10:56 UTC, OliviaGometz commented on src/lib/DatePicker/CalendarCell/CalendarCell.test.js
> +import { DropdownContext } from '../../Dropdown/DropdownContext';
idem, à placer juste au-dessus du DateContextProvider :D

2021-02-15 10:56 UTC, OliviaGometz commented on src/lib/DatePicker/CalendarGrid/CalendarGrid.test.js
> +import { DropdownContext } from '../../Dropdown/DropdownContext';
re l'ordre des imports (c'est primordial oui oui 😆 )

2021-02-15 10:56 UTC, OliviaGometz commented on src/lib/DatePicker/DatePicker.js
> +            (position === 'isBefore'
quitte à faire ça, ce serait peut-être plus "simple" d'écrire cette fonction-là comme ça : 

`referenceDateCondition = (dateValue, dateMin, dateMax) => {` (avec dateMin et dateMax qui sont optionnels) : de cette manière, non seulement tu peux faire les 2 tests en un, mais en plus tu évites de passer des string pour les isBefore et isAfter (sans perdre en lisibilité !) 😄

2021-02-15 10:56 UTC, OliviaGometz commented on src/lib/DatePicker/DatePicker.js
> +            (position === 'isBefore'
de même, pour le nommage de cette fonction, un `isValidDate` (par exemple) serait peut-être plus clair à la relecture ? :)

2021-02-15 10:56 UTC, OliviaGometz commented on src/lib/Dropdown/Dropdown.stories.js
> +import DropdownControl from './DropdownControl';
aaah c'est ton prettier qui t'as mis les imports par ordre alpha ? parce que si c'est ça faut qu'on repasse sur tous les fichiers, là traditionnellement on aurait laissé dropdown et dropdowncontrol en dernier :/

2021-02-15 12:48 UTC, fanya3 commented on src/lib/Dropdown/Dropdown.stories.js
> +import DropdownControl from './DropdownControl';
alors nan c'est moi! au bout d'un moment quand y a trop d'import moi je les mets par ordre alphabétique! sorry! :sweat_smile:

2021-02-15 14:44 UTC, OliviaGometz requested changes
J'ai trouvé quelques bugs de comportement dans le DatePicker (mais je ne sais pas si c'était pas là avant du coup, dans le doute je remonte) 👍 

- Quand une date est renseignée et qu'on passe en readonly ou en disabled, le champ est vidé (ce qui est pas normal, surtout pour le readonly)
- Une fois que j'ai cliqué sur le champ du datePicker, il est impossible de vider le champ pour ne renseigner aucune date (y'en a toujours une qui est settée, peu importe que je clique en-dehors du datepicker pour en sortir ou que j'efface manuellement la saisie)
- si je change une props visuelle (isRounded, colorStatus, et même la locale), ça vide le champ :(

2021-02-15 14:44 UTC, OliviaGometz commented on src/lib/Dropdown/Dropdown.stories.js
> +            <Dropdown hasOverlay={false}>
à la limite, pour éviter d'avoir 50 stories dont une avec un nom à la Proust, on peut fusionner les 2 premières et utiliser un `boolean('Has overlay', true)` sur le `hasOverlay`, en ajoutant autour du ButtonGroup ce même booléen pour afficher le bouton uniquement si y'a pas d'overlay (comme ça, on voit bien la diff) 😄

2021-02-16 09:53 UTC, OliviaGometz approved these changes

2021-02-16 10:05 UTC, merged