PGF-232 - EPIC DatePicker
PayGreen/paygreen-ui pull request #85
Opened 2020-08-13 13:15 UTC by pierrick-lefebvre

## Description
This PR contains the new component DatePicker.

## How to test ?
- Launch storybook with `yarn install`, then `yarn storybook`
- Try a local integration of the DatePicker in a form to use it in real condition

2020-08-20 12:17 UTC, MattMattC approved these changes

2020-10-01 16:01 UTC, OliviaGometz requested changes

2020-10-01 16:01 UTC, OliviaGometz commented on src/lib/DatePicker/localeConfig.js
> +export default config;
Bon je sais pas si c'est voulu, mais j'ai l'impression que ce fichier contient plein de trucs dont on n'a pas l'utilité, peut-être qu'il vaudrait mieux sauvegarder ça ailleurs au cas où on veut s'en servir un jour, et on garde pour l'instant que l'utile ? :)

2020-10-01 16:03 UTC, OliviaGometz commented
Du coup @pierrick-lefebvre, j'ai fait un push sur ton epic pour virer le style du Calendar, rétablir le style initial de la Popin (éviter les bugs ailleurs) et ajouter le fix de la popin dans le style du composant DatePicker, comme ça on aura moins de risques d'effet de bord et c'est plus propre :)

2020-10-02 08:12 UTC, pierrick-lefebvre commented on src/lib/DatePicker/Calendar/style/index.js
> +
Ce fichier a été supprimé lors d'un précédent refacto

2020-10-02 08:13 UTC, pierrick-lefebvre commented on src/lib/DatePicker/Calendar/Calendar.js
> +} from '../../../shared/constants';
La ligne comportant le CalendarBase à été supprimée avec le dossier de style lors d'un précédent refacto

2020-10-02 08:32 UTC, pierrick-lefebvre commented on src/lib/DatePicker/CalendarCell/CalendarCell.js
> +                    ? date.format('DD/MM/YYYY') ===
Utilisation des constantes fournies par le fichier de locales

2020-10-02 08:33 UTC, pierrick-lefebvre commented on src/lib/DatePicker/CalendarCell/CalendarCell.js
> +            colorStatus={colorStatus}
Corrigé

2020-10-02 08:36 UTC, pierrick-lefebvre commented on src/lib/DatePicker/CalendarCell/CalendarCell.js
> +            {date ? date.format('D') : null}
Corrigé, utilisation du isRequired et donc suppression du test _null_ et de la valeur par défaut

2020-10-02 08:41 UTC, pierrick-lefebvre commented on src/lib/index.js
> +import DatePicker from './DatePicker/DatePicker/DatePicker';
Corrigé, les fichiers concernant le DatePicker ont été move dans le dossier racine DatePicker. Les sous-composants, eux, restent dans leur sous-dossier respectives

2020-10-02 08:43 UTC, pierrick-lefebvre commented on src/shared/constants.js
> +        datePicker: 'DatePicker' + folderSeparator,
Corrigé, la story du DatePicker se trouve maintenant dans la section _Form elements_

2020-10-02 08:46 UTC, pierrick-lefebvre commented on src/lib/DatePicker/DatePicker/DatePicker.stories.js
> +storiesOf(folder.form + folder.sub.datePicker + 'DatePicker', module)
Corrigé

2020-10-02 08:50 UTC, pierrick-lefebvre commented on src/lib/DatePicker/CalendarCell/style/base.js
> +const enabled = css`
Corrigé

2020-10-02 08:56 UTC, pierrick-lefebvre commented on src/lib/DatePicker/CalendarCell/style/index.js
> +
Corrigé

2020-10-02 09:21 UTC, pierrick-lefebvre commented on src/lib/DatePicker/CalendarGrid/CalendarGrid.js
> +    const [month, setMonth] = useContext(MonthContext);
Je passe dans mon MonthContext un useState avec un state et son setter. Si je ne récupère pas le contenu de mon contexte en le déstructurant dans un tableau, alors j'obtiens un tableau plus compliqué à manipuler je trouve. Je ne sais pas s'il y a une alternative pour ce cas de figure.

2020-10-02 09:28 UTC, pierrick-lefebvre commented on src/lib/DatePicker/CalendarNavbar/CalendarNavbar.js
> +    };
Corrigé

2020-10-02 09:32 UTC, pierrick-lefebvre commented on src/lib/DatePicker/CalendarNavbar/CalendarNavbar.js
> +                htmlTag={iconHtmlTagOptions.button}
Corrigé

2020-10-02 09:39 UTC, pierrick-lefebvre commented on src/lib/DatePicker/CalendarNavbar/style/index.js
> +
J'ai supprimé quelques sauts de ligne et réorganiser le CSS, je trouve ça plus lisible de ranger le CSS en fonction des éléments modifiés (font, espacement, curseur, etc.). Si c'est toujours gênant, je supprimerais tout mes sauts de ligne :-)

2020-10-02 09:44 UTC, pierrick-lefebvre commented on src/lib/DatePicker/DatePicker/DatePicker.js
> +        'pg-' + locale,
Corrigé :+1:

2020-10-02 09:50 UTC, pierrick-lefebvre commented on src/lib/DatePicker/DatePicker/DatePicker.js
> +        localeConfig['pg-' + locale] ? localeConfig['pg-' + locale] : null,
Héhé ... Visiblement je devais pas être très réveillé à ce moment, mais oui, ça peut poser problème car la locale par défaut c'est _en_ et la localeConfig correspondante fourni par **moment** ne correspond pas à nos formats de date + le dimanche en premier jour de la semaine. L'alternative que tu as proposé corrige ce problème donc tout est bon :+1:

2020-10-02 09:52 UTC, pierrick-lefebvre commented on src/lib/DatePicker/DatePicker/DatePicker.js
> +                    {...rest}
Corrigé

2020-10-02 09:53 UTC, pierrick-lefebvre commented on src/lib/DatePicker/DatePicker/DatePicker.js
> +    hasHelpButton: false,
C'est retiré

2020-10-02 10:04 UTC, pierrick-lefebvre commented on src/lib/DatePicker/DatePicker/DatePicker.js
> +    inputRef: PropTypes.oneOfType([
Un problème super bizarre : l'ajout de blockWidth fait disparaître la story de Storybook, j'investigue.

2020-10-02 10:27 UTC, pierrick-lefebvre commented on src/lib/DatePicker/DatePicker/DatePicker.js
> +                    <Popin hasStyle={false}>
La props a déjà été retirée dans un refacto précédent

2020-10-02 10:27 UTC, pierrick-lefebvre commented on src/lib/Popin/Popin.js
> +    hasStyle: PropTypes.bool,
Déjà été retirée dans un refacto précédent

2020-10-02 10:27 UTC, pierrick-lefebvre commented on src/lib/DatePicker/CalendarCell/style/index.js
> +    transition: all ${props => props.theme.transition.xs}
Corrigé

2020-10-02 10:31 UTC, pierrick-lefebvre commented on src/lib/DatePicker/DatePicker/DatePicker.js
> +        const monthDiff = selectedDate.format('M') - moment().format('M');
Oui, car autrement on vient soustraire deux **entitées moment**, donc des objets qui ne peuvent donc pas être soustraits avec l'opérateur **-**. moment fourni une fonction appelé **diff** mais son comportement fait qu'elle ne convient pas dans notre cas d'usage. D'où le fait de tout faire manuellement pour correctement déterminé la différence de mois et d'années.

2020-10-02 12:12 UTC, pierrick-lefebvre commented on src/lib/DatePicker/localeConfig.js
> +        ),
C'est le format de fichier demandé par Moment pour que les locales soient valides.

2020-10-02 12:14 UTC, pierrick-lefebvre commented on src/lib/DatePicker/localeConfig.js
> +        meridiem: function(hours, minutes, isLower) {
Pour le bon fonctionnement de la locale, par précaution j'ai repris le format de fichier donné par moment en incluant tout les champs existants.

2020-10-02 12:14 UTC, pierrick-lefebvre commented on src/lib/DatePicker/localeConfig.js
> +            return number + (number === 1 ? 'er' : 'e');
Idem que pour la remarque ci-dessus

2020-10-02 12:15 UTC, pierrick-lefebvre commented on src/lib/DatePicker/localeConfig.js
> +        weekdaysMin: 'Su_Mo_Tu_We_Th_Fr_Sa'.split('_'),
Idem que pour la remarque ci-dessus

2020-10-02 12:15 UTC, pierrick-lefebvre commented on src/lib/DatePicker/localeConfig.js
> +        monthsShort: 'jan._feb._mar._apr._may_jun._jul._aug._sep._oct._nov._dec.'.split(
Idem que pour la remarque ci-dessus

2020-10-02 12:15 UTC, pierrick-lefebvre commented on src/lib/DatePicker/localeConfig.js
> +        },
Idem que pour la remarque ci-dessus

2020-10-02 12:17 UTC, pierrick-lefebvre commented on src/lib/DatePicker/localeConfig.js
> +export default config;
Idem que pour la remarque ci-dessus
Je vais tenter de supprimer certains des éléments de ces fichiers que nous n'utiliserons pas pour voir si une locale incomplète pause problème à l'intégration :-)

2020-10-02 12:44 UTC, pierrick-lefebvre commented on src/lib/DatePicker/localeConfig.js
> +export default config;
Après quelques tests cela semble fonctionner correctement, j'ai donc viré tout ce qui ne nous était pas utile du fichier de config :-)

2020-10-02 12:47 UTC, pierrick-lefebvre commented on src/lib/DatePicker/DatePicker/DatePicker.js
> +    inputRef: PropTypes.oneOfType([
C'est corrigé, un petit problème d'imports

2020-10-02 12:52 UTC, pierrick-lefebvre commented on src/lib/DatePicker/CalendarGrid/CalendarGrid.js
> +    const [month, setMonth] = useContext(MonthContext);
C'est corrigé, j'ai appris un truc :+1:

2020-10-02 15:24 UTC, OliviaGometz requested changes

2020-10-02 15:24 UTC, OliviaGometz commented on src/lib/DatePicker/DatePicker.stories.js
> +            placeholder={text('Placeholder', moment().format('DD/MM/YYYY'))}
en vrai met pas de champ text pour ça, pouvoir changer la date c'est suffisant, pas la peine de pouvoir custom le placeholder, ça alourdit la story pour pas grand chose vu que c'est vraiment une fonctionnalité basique :)

2020-10-02 15:47 UTC, OliviaGometz approved these changes

2020-10-05 09:37 UTC, fanya3 approved these changes

2020-10-05 09:47 UTC, merged