PGF-255 : Amélioration de la sidebar
PayGreen/paygreen-ui pull request #90
Opened 2020-09-08 06:57 UTC by fanya3

## How to test?
- yarn storybook
- go to sidebar/ sidebarMenu/ sidebarMenuCategory and test open/close arrow

2020-09-14 06:24 UTC, MattMattC approved these changes

2020-09-14 08:57 UTC, OliviaGometz requested changes

2020-09-14 08:57 UTC, OliviaGometz commented on src/lib/SidebarMenu/SidebarMenu.js
> +                return child;
aller, pour pinailler, je dirais bien qu'un switch ici ce serait encore plus propre <3

2020-09-14 08:57 UTC, OliviaGometz commented on src/lib/SidebarItem/style/base.js
> +    &:focus {
Là le souci c'est qu'en faisait ça, tu retires le style aux SidebarItem qui sont contenus dans des a :/ ce qui veut dire qu'en effet, l'effet marche au hover, mais c'est au hover de la div, pas de son parent a.
Donc le active et le focus ne fonctionneront plus !

Il faudrait que le style au hover soit conditionnel : si le sidebarItem a un htmlTag div, alors il sera dans les a:hover & (et compagnie). Si c'est un button, alors il sera dans le &:hover et compagnie :)

2020-09-14 08:57 UTC, OliviaGometz commented on src/lib/SidebarItem/SidebarItem.js
>                      htmlTag={iconHtmlTagOptions.button}
Là vu que le SidebarItem peut être un button, il faut que l'Icon soit un span tout simple, sinon tu vas avoir une erreur en console (un button peut pas encapsuler un autre button ou un a, par exemple, ce serait inutilisable et illogique). :)

Le span c'est la valeur par défaut de l'Icon, donc tu peux retirer la ligne htmlTag et l'import :)

2020-09-14 08:57 UTC, OliviaGometz commented on src/lib/SidebarItem/SidebarItem.js
> +            {isClickable ? (
Là du coup, puisqu'on peut faire en sorte que le SidebarItem soit un button, on peut supprimer la props "isClickable" et la remplacer par un if htmlTag === sidebarItemHtmlTagOptions.button, ça fera une props de moins à gérer et on obtient exactement l'effet qu'on veut ! :D

2020-09-14 08:57 UTC, OliviaGometz commented on src/lib/SidebarItem/style/index.js
>      display: grid;
Rien à voir, mais en ouvrant le fichier j'ai une erreur à cause de la ligne padding sur deux lignes, si tu veux fixer ça en même temps avec un `padding: ${props =>
        props.theme.space.xs + ' ' + props.theme.space[props.paddingLateral]};` ce serait top, ça évitera des erreurs futures <3

2020-09-14 08:58 UTC, OliviaGometz commented
Hormis les fix ci-dessus, tout est nickel (recette réalisée aussi, c'est propre), donc dès que c'est corrigé c'est mergé ! 😄

2020-09-14 15:28 UTC, OliviaGometz requested changes

2020-09-14 15:28 UTC, OliviaGometz commented on src/lib/SidebarItem/style/index.js
> +    & > .icon:last-of-type {
aaaah fock on va avoir un souci : si on a un icon "flèche" mais pas d'icon décoratif avant, l'icon flèche va pas se placer au bon endroit :/

2020-09-14 15:37 UTC, fanya3 commented on src/lib/SidebarItem/style/index.js
> +    & > .icon:last-of-type {
ah ben quand j'ai mis ça je me suis dit qu'on aurait toujours à minima l'icon décoratif... pas toi???

2020-09-15 07:14 UTC, OliviaGometz approved these changes

2020-09-15 07:57 UTC, merged