PGF-263 :  amélioration layout DaTable sur mobile
PayGreen/paygreen-ui pull request #91
Opened 2020-09-10 06:58 UTC by fanya3

## How to test?
- yarn storybook
- go to DaTable : test DaTableHead layout on small screens  & test width 
- go to DaTableHead : test DaTableHead layout on small screens

2020-09-14 06:21 UTC, MattMattC approved these changes

2020-09-14 10:04 UTC, OliviaGometz requested changes

2020-09-14 13:12 UTC, fanya3 commented on src/lib/DaTableHeadCell/style/base.js
> +            flex:1;
oui , car sans ça donne ça :
![Capture d’écran de 2020-09-14 15-10-57](https://user-images.githubusercontent.com/43522873/93090162-a4e4a380-f69c-11ea-8e9a-67a7c048b0e0.png)

2020-09-14 13:16 UTC, fanya3 commented on src/lib/DaTableHeadCell/style/base.js
> +            max-width: calc(${props => '100% - ' + math(props.theme.icon.size.sm + ' + ' + props.theme.space.lg)});
c'est pour que peu importe la max-width passée aux children genre un input de search, quand on est en largeur mobile donc assez étroit, ben l'input est toujours un peu + court et occupe pas toute la largeur, et ça laisse les enchaînements  de boutons + lisibles, car rien ne vient les séparer visuellement, je trouve ça créé un meilleur eye tracking,  surtout si on commence à avoir pas mal de lignes...
![Capture d’écran de 2020-09-14 15-15-00](https://user-images.githubusercontent.com/43522873/93090537-2ccaad80-f69d-11ea-9383-d08e03906820.png)

2020-09-14 15:07 UTC, fanya3 commented on src/lib/DaTableHeadCell/style/base.js
> +            align-items:center;
encore prettier qui m'a laissée tomber... g pas vu :(

2020-09-14 15:07 UTC, fanya3 commented on src/lib/DaTableHeadCell/style/base.js
> +        font-size: ${props => props.theme.font.size.sm};
ok pour le texte

2020-09-14 15:13 UTC, fanya3 commented
@OliviaGometz j'ai fait les tests en passant tout soit en sm ou en xs. je préfère vraiment le sm (sauf pour le texte que j'ai repassé en xs) pour permettre un clic au doigt "confortable" sur mobile (sachant que si on a des tableheadcell sans children les boutons de sort peuvent être assez rapprochés). après avoir comparé avec d'autres interfaces et mis les images sur mon mobile (qui est mon vieux samsung Note3 donc l'écran est énooorme!) 
![test mobile](https://user-images.githubusercontent.com/43522873/93103799-5a1f5780-f6ad-11ea-938f-474dcc7d3e25.png)

2020-09-14 15:14 UTC, fanya3 commented on src/lib/DaTableHeadCell/style/base.js
> +                margin: 0 ${props => props.theme.space.xs};
ok

2020-09-14 15:15 UTC, fanya3 commented on src/lib/DaTableHeadCell/style/base.js
> +                        props.theme.icon.size.sm +
petit pour moi....

2020-09-14 15:16 UTC, fanya3 commented on src/lib/DaTableHeadCell/style/base.js
> +                height: ${props => props.theme.icon.size.sm};
petit pour moi

2020-09-15 08:56 UTC, OliviaGometz requested changes

2020-09-15 08:56 UTC, OliviaGometz commented on src/lib/DaTableHead/DaTableHead.test.js
> +            <DaTableHeadCell isCheckbox={true} theme={ThemeDefault}>
Si c'est une checkbox, pourquoi y'a du texte ? 🤔

2020-09-15 09:00 UTC, fanya3 commented on src/lib/DaTableHead/DaTableHead.test.js
> +            <DaTableHeadCell isCheckbox={true} theme={ThemeDefault}>
nan mais j'ai fait une crotte sur ce truc!! le children c'est une Checkbox!!  my bad

2020-09-15 10:00 UTC, OliviaGometz approved these changes

2020-09-15 10:04 UTC, merged