PGF-253: fix multiple components
PayGreen/paygreen-ui pull request #93
Opened 2020-09-17 13:28 UTC by OliviaGometz

- Amélioration gestion de l'ombre du Main
- Fix largeur des labels et outline des inputs cachés pour le Radio et le Checkbox
- Réorganiser le CSS (hiérarchie des classes CSS) dans le base.js du DaTableHeadCell
- Retrait de la props isCheckbox dans les composants DaTable[quelque chose]
- Composants de tableau : replacer MenuIcon par ListIcon (icon pour grouper)
- Grille du composant Message : retirer le "justify-items : center" et changer le display grid en inline-grid (pour les messages courts)
- Ajout de marges top et bottom custom (non responsives) sur Message
- Faire en sorte que le ListItem puisse être utilisé comme un <button> + refacto des props de ce composant

2020-09-17 15:16 UTC, fanya3 requested changes

2020-09-17 15:16 UTC, fanya3 commented on src/lib/Checkbox/style/index.js
> +        outline: none;
du coup je suis allée checker, en fait il faudrait le rajouter aussi sur Radio pour éviter le contour moche..

![radio outline](https://user-images.githubusercontent.com/43522873/93490807-3c4e2e80-f909-11ea-8db0-3bb94dec8586.png)

2020-09-17 15:16 UTC, fanya3 commented on src/lib/Checkbox/style/index.js
> +    display: flex; /* avoid 100% large label (for hover) */
bon ben faut le faire sur le composant Radio aussi, y a le même effet de hover! :)

2020-09-17 15:39 UTC, fanya3 commented on src/lib/RadioIcon/style/index.js
> +    display: flex; /* avoid 100% large label (for hover) */
du coup en le faisant ici moi j'ai un bug d'affichage dans storybook... mais tu as peut etre confondu avec Radio ??
![radio icon](https://user-images.githubusercontent.com/43522873/93493959-c350d600-f90c-11ea-8123-214dca20435c.png)

2020-09-18 08:06 UTC, OliviaGometz commented on src/lib/DaTableRow/DaTableRow.test.js
> +                <Checkbox theme={ThemeDefault} id="select"/>
Ah ah t'inquiètes j'avais pas tilté à la relecture non plus ! 😄

2020-09-18 16:20 UTC, fanya3 approved these changes

2020-09-18 16:46 UTC, fanya3 commented
c'est tout bon!!! ::)  
après vu que tu sembles lancée sur une espèce de perfection, je me suis fait la réflexion que quand tu testes dans storybook le Dropdown, celui avec le badge semble avoir un bug paske vu que c'est le seul des 3 où au clic la flèche ne bouge pas...

2020-09-22 12:24 UTC, fanya3 approved these changes

2020-09-22 13:57 UTC, merged