Pgf-15: update du composant Icon pour y intégrer un badge avec numéro
PayGreen/paygreen-ui pull request #94
Opened 2020-09-17 14:05 UTC by fanya3

## Voir PGF-15 pour le détails des modifs! (sur Icon et minifix sur FormControl)
 
## Comment tester? 
- yarn storybook
- go to FormControl (rien n'a changé)
- go to Icon with badge number : 
       - tester le changement de valeur à 0 (ça disparait) et au dessus de 99
       - tester le changement de couleur (theme, status, wab)

2020-09-22 10:06 UTC, OliviaGometz commented on src/lib/FormControl/FormControl.js
> +                }
j'ai un trou de mémoire, on fait ça pour éviter les erreurs quand on essaie de cloner un enfant qui n'existe pas ?

2020-09-22 12:05 UTC, fanya3 commented on src/lib/FormControl/FormControl.js
> +                }
oui et donc spécifiquement quand on a des enfants dont le rendu est conditionnel. je me suis aperçue qu'il le fallait quand j'ai fait mon analyse/test technique pour le contrôle des champs de formulaire ds le BO. ex: si j'ai un composant Message associé à un DaInput le tout englobé par un Formcontrol et que je veux afficher le Message que si j'ai un message d'erreur spécifique sur ce DaInput, j'en ai besoin sinon le FormControl me pète une erreur :)

2020-09-22 12:07 UTC, fanya3 commented on src/lib/FormControl/FormControl.js
> +                }
` <FormControl
            required={true}
	    colorStatus={errors.email? "warning" : "default"}
        >
            <DaLabel>Email label</DaLabel>

            <DaInput
	        name="email"
                placeholder="your email here"
                blockWidth={inputWidthOptions.sm}
                hasHelpButton={true}
								inputRef={register({
								          required: "Required",
								          pattern: {
								            value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
								            message: "invalid email address"
								          }
					        })}
            />

            {errors.email && 
                <Message
                    arrowBlock={arrowBlockOptions.topLeft}
                    blockWidth={inputWidthOptions.sm}
                >
                    {errors.email.message}}
                </Message>
            )
        </FormControl>`

2020-09-22 12:09 UTC, fanya3 commented on src/lib/FormControl/FormControl.js
> +                }
`import React from "react";
import { useForm } from "react-hook-form";

const Example = () => {
  const { handleSubmit, register, errors } = useForm();
  const onSubmit = values => console.log(values);

  return (
    <form onSubmit={handleSubmit(onSubmit)} noValidate>
      <FormControl
            required={true}
	    colorStatus={errors.email? "warning" : "default"}
        >
            <DaLabel>Email label</DaLabel>

            <DaInput
		name="email"
                placeholder="your email here"
                blockWidth={inputWidthOptions.sm}
                hasHelpButton={true}
		inputRef={register({
		required: "Required",
		pattern: {
		value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
		message: "invalid email address"
		}
	})}
  />

            {errors.email && 
                <Message
                    arrowBlock={arrowBlockOptions.topLeft}
                    blockWidth={inputWidthOptions.sm}
                >
                    {errors.email.message}}
                </Message>
            )
        </FormControl>

      <button type="submit">Submit</button>
    </form>
  );
};				`

2020-09-22 12:10 UTC, fanya3 commented on src/lib/FormControl/FormControl.js
> +                }
import React from "react";
import { useForm } from "react-hook-form";

const Example = () => {
  const { handleSubmit, register, errors } = useForm();
  const onSubmit = values => console.log(values);

  return (
    <form onSubmit={handleSubmit(onSubmit)} noValidate>
      <FormControl
            required={true}
	    colorStatus={errors.email? "warning" : "default"}
        >
            <DaLabel>Email label</DaLabel>

            <DaInput
		name="email"
                placeholder="your email here"
                blockWidth={inputWidthOptions.sm}
                hasHelpButton={true}
		inputRef={register({
		required: "Required",
		pattern: {
		value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
		message: "invalid email address"
		}
	})}
  />

            {errors.email && 
                <Message
                    arrowBlock={arrowBlockOptions.topLeft}
                    blockWidth={inputWidthOptions.sm}
                >
                    {errors.email.message}}
                </Message>
            )
        </FormControl>

      <button type="submit">Submit</button>
    </form>
  );
};

2020-09-22 12:12 UTC, fanya3 commented on src/lib/FormControl/FormControl.js
> +                }
![Capture d’écran de 2020-09-22 14-11-59](https://user-images.githubusercontent.com/43522873/93880371-aab23880-fcdd-11ea-93df-681464ac9f75.png)

2020-09-22 13:31 UTC, OliviaGometz requested changes

2020-09-23 06:14 UTC, fanya3 commented
en testant hier dans le BO le FormControl (pour verifier qu'avec le switch à la place des if  le reactclone marchait toujours bien) , j'ai testé les Icons avec le badge nombre et j'ai eu ça :  du coup j'ai rajouté un text-align : center;
![Capture d’écran de 2020-09-22 17-50-22](https://user-images.githubusercontent.com/43522873/93973511-966d4a80-fd74-11ea-8d69-09f55a261e70.png)

2020-09-24 12:08 UTC, OliviaGometz requested changes

2020-09-24 12:08 UTC, OliviaGometz commented on package-lock.json
> +  "name": "@paygreen/paygreen-ui",
Mais naaaaaaan me commit pas le package-lock ! :(

2020-09-24 13:02 UTC, pierrick-lefebvre approved these changes

2020-09-25 07:54 UTC, OliviaGometz approved these changes

2020-09-25 07:54 UTC, merged