PGF-104: uniformize stories labels
PayGreen/paygreen-ui pull request #96
Opened 2020-09-28 09:37 UTC by OliviaGometz

WIP (pour pas l'oublier)

2020-10-12 08:05 UTC, OliviaGometz commented on src/shared/labels.js
> +    ascSort: 'ASC sort (need Sort icon active)',
là ça me semble trop spécifique aussi, le sort/groupIcon (et ascSort, surtout !)

2020-10-12 08:05 UTC, OliviaGometz commented on src/shared/labels.js
> +    colorStyle: 'Color style',
passe le colorStyle au-dessus du colorType si tu fais pas par ordre alphabétique, ce sera plus logique :)

2020-10-12 08:05 UTC, OliviaGometz commented on src/shared/labels.js
> +    withSortIcon: 'With sort icon',
Trop spécifique je trouve :) (idem pour celui du dessous)

2020-10-12 08:05 UTC, OliviaGometz commented on src/shared/labels.js
> +    withCounter: 'With counter',
hasCounter plutôt, pour coller à la props

2020-10-12 08:05 UTC, OliviaGometz commented on src/shared/labels.js
> +    compensatedButtonMargins: 'Compensate buttons margin',
trop spécifique, il sert qu'à un seul endroit sur un seul composant :)

2020-10-12 08:05 UTC, OliviaGometz commented on src/shared/labels.js
> +    placeholder: 'Placeholder',
on s'en sert vraiment ? Ca a peu d'intérêt de custom un placeholder pourtant :O

2020-10-12 08:05 UTC, OliviaGometz commented on src/shared/labels.js
> +    dotStyle: 'Dot Style',
peut-être qu'on peut grouper les button et dot style en juste "style" (idem pour size et align) :)

2020-10-12 08:05 UTC, OliviaGometz commented on src/shared/labels.js
> +    paddingBottom: 'Padding bottom',
On n'a pas de paddingLateral ?

2020-12-07 10:45 UTC, OliviaGometz commented on src/lib/Card/Card.stories.js
> +                labels.borderTopStyle,
vraiment utile d'avoir un label pour border-top style ? (je crois pas qu'on l'utilise ailleurs que dans ce composant-là et ce cas-là) :)

2020-12-07 10:45 UTC, OliviaGometz commented on src/lib/DaTableHeadCell/DaTableHeadCell.stories.js
> +                boolean(labels.withGroupIcon, false) ? (
beaucoup de spécifique dans ce fichier, à voir si ça a du sens de les mettre dans les labels partagés :)

2021-05-14 15:29 UTC, OliviaGometz commented on src/lib/Card/Card.stories.js
> +                labels.borderRadius,
Peut-être que `radiusSize` serait plus approprié :)

2021-05-14 15:29 UTC, OliviaGometz commented on src/lib/Corner/Corner.stories.js
> +            hasCenteredPopin={boolean(labels.centeredPopin, false)}
c'est pas la peine je pense, seul le Corner a cette props-là actuellement :)

2021-05-14 15:29 UTC, OliviaGometz commented on src/lib/DaTextarea/DaTextarea.stories.js
> +            hasCounter={boolean(labels.withCounter, true)}
hasCounter du coup, plutôt ? :)

2021-05-14 15:29 UTC, OliviaGometz commented on src/shared/labels.js
> +    borderRadius: 'Border radius',
j'me répète c'est ouf, au moins je suis cohérente xD

2021-05-14 15:29 UTC, OliviaGometz commented on src/shared/labels.js
> +    centeredPopin: 'Centered popin',
JE SUIS COHERENTE LALALA <3

2021-05-31 13:44 UTC, OliviaGometz commented on src/lib/DaHelp/DaHelp.stories.js
> +                labels.fieldSize,
labels à ajouter sur ce fichier

2021-05-31 13:44 UTC, OliviaGometz commented on src/lib/DaInput/DaInput.stories.js
>              icon={boolean('Has icon', true) ? <SearchIcon /> : null}
Labels à ajouter sur ce fichier

2021-05-31 13:44 UTC, OliviaGometz commented on src/lib/DaSelect/DaSelect.stories.js
>              icon={boolean('Has icon', true) ? <ListIcon /> : null}
label à ajouter sur ce fichier

2021-06-30 19:09 UTC, fanya3 requested changes

2021-06-30 20:20 UTC, fanya3 commented
![Capture d’écran de 2021-06-30 22-10-49](https://user-images.githubusercontent.com/43522873/124025217-79933100-d9f0-11eb-86fa-ac8b73c5ba9b.png)
![Capture d’écran de 2021-06-30 22-11-06](https://user-images.githubusercontent.com/43522873/124025219-7ac45e00-d9f0-11eb-8b72-079f64e13325.png)
![Capture d’écran de 2021-06-30 22-11-19](https://user-images.githubusercontent.com/43522873/124025221-7ac45e00-d9f0-11eb-9d02-e52ac0cfcc04.png)

en recettant les stories que tu as revues pour mettre des hooks fonctionnels (c'est mieux!), je me demandais si c'était normal le débord dans le menu group... en format mobile, par rapport au Header où le menu pour le profil user est aligné avec le header, sur le menugroup le header est en retrait et les menus qui s'ouvrent/ferment débordent par le haut/droite/gauche ?

2021-07-01 12:41 UTC, OliviaGometz commented on src/lib/AutonomousInput/AutonomousInput.stories.js
> +            placeholder="Your email..."
Nope, c'était pas très utile je trouve ! :)

2021-07-01 13:04 UTC, OliviaGometz commented
@fanya3 pour répondre à ton commentaire précédent : oui, c'est "normal", ça fait partie des trucs qu'on doit améliorer mais le ticket traîne depuis des plombes 😢 c'est storybook 6 et ses changements à la con, nos composants à nous sont nickels. Tant qu'on utilisera pas leur nouvelle structure, on aura le souci 😞

2021-07-01 13:24 UTC, fanya3 commented on src/lib/AutonomousInput/AutonomousInput.stories.js
> +            placeholder="Your email..."
ok!

2021-07-01 13:36 UTC, fanya3 approved these changes

2021-07-01 13:47 UTC, merged